default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: shivansh
  host: localhost

development:
  <<: *default
  database: chat_app_development

test:
  <<: *default
  database: chat_app_test

production:
  <<: *default
  database: chat_app_production
  username: chat_app
  password: <%= ENV['CHAT_APP_DATABASE_PASSWORD'] %>
